export const HEROES = {
  gemini: {
    id: "gemini",
    name: "Gemini",
    key: "gemini",
    blurb: "Twin Cosmo · Galaxian Explosion",
    speed: 220,
    arriveDistance: 8,
    attackRange: 90,
    attackCooldownMs: 280,
    attackDamage: 34,
    specialChargeMs: 10 * 1000,
    specialRange: 420,
    specialDamage: 999,
    specialName: "GALAXIAN EXPLOSION",
    specialStyle: "galaxian",
    scale: 0.9,
    accent: 0x6ec8e0,
  },
  virgo: {
    id: "virgo",
    name: "Virgo",
    key: "virgo",
    blurb: "Buddha Cosmo · 108 prayer beads",
    speed: 200,
    arriveDistance: 8,
    attackRange: 110,
    attackCooldownMs: 320,
    attackDamage: 28,
    specialChargeMs: 10 * 1000,
    specialRange: 400,
    specialDamage: 999,
    specialName: "TENBU HORIN",
    specialStyle: "beads",
    scale: 0.9,
    accent: 0xe8d48a,
  },
  sagittarius: {
    id: "sagittarius",
    name: "Sagittarius",
    key: "sagittarius",
    blurb: "Golden archer · Atomic Thunderbolt",
    speed: 245,
    arriveDistance: 8,
    attackRange: 130,
    attackCooldownMs: 260,
    attackDamage: 30,
    specialChargeMs: 10 * 1000,
    specialRange: 460,
    specialDamage: 999,
    specialName: "ATOMIC THUNDERBOLT",
    specialStyle: "thunderbolt",
    scale: 0.88,
    accent: 0xf0c45a,
  },
};

export const GAME = {
  width: 960,
  height: 640,
  durationMs: 2 * 60 * 1000,
  patchMaxHp: 100,
  // Legacy aliases (Gemini defaults) used where hero isn't in scope yet
  geminiSpeed: 220,
  geminiArriveDistance: 8,
  geminiAttackRange: 90,
  geminiAttackCooldownMs: 280,
  geminiAttackDamage: 34,
  doubleClickMs: 280,
  specialChargeMs: 10 * 1000,
  specialAttackRange: 420,
  specialAttackDamage: 999,
  enemySpeed: 55,
  enemyHp: 30,
  enemyDamage: 5,
  enemyAttackCooldownMs: 900,
  spawnIntervalStartMs: 2800,
  spawnIntervalMinMs: 1600,
  // Broccoli pests — weights shift as the match progresses
  enemyTypes: {
    squirrel: {
      key: "enemy-squirrel",
      label: "Squirrel",
      hp: 30,
      speed: 55,
      damage: 5,
      attackCooldownMs: 900,
      scale: 0.85,
      shadowW: 34,
      shadowH: 12,
      body: { w: 40, h: 44, ox: 16, oy: 14 },
    },
    aphid: {
      key: "enemy-aphid",
      label: "Aphid",
      hp: 14,
      speed: 95,
      damage: 3,
      attackCooldownMs: 650,
      scale: 0.7,
      shadowW: 24,
      shadowH: 10,
      body: { w: 28, h: 30, ox: 18, oy: 18 },
      packChance: 0.55,
    },
    worm: {
      key: "enemy-worm",
      label: "Cabbage Worm",
      hp: 70,
      speed: 32,
      damage: 9,
      attackCooldownMs: 1100,
      scale: 0.95,
      shadowW: 46,
      shadowH: 14,
      body: { w: 48, h: 36, ox: 16, oy: 22 },
    },
  },
  athenaIntervalMs: 15 * 1000,
  athenaHealAmount: 35,
  // Pseudo-3D (WC3-style tilted view)
  pseudo3d: {
    farScale: 0.72,
    nearScale: 1.1,
    spriteSquash: 0.9,
    shadowAlpha: 0.34,
  },
};

export const COLORS = {
  ground: 0x1a2a22,
  groundAccent: 0x24382d,
  gemini: 0xd4b45a,
  geminiAccent: 0x6ec8e0,
  broccoli: 0x3f8f4a,
  broccoliStem: 0x8fbf5a,
  enemy: 0xc45c48,
  enemyEye: 0xf2e6c8,
  hud: "#f3efe4",
  hudMuted: "#a8b5aa",
  danger: "#e07a5f",
  win: "#8fd19e",
};
