export const HEROES = {
  aries: {
    id: "aries",
    name: "Aries",
    key: "aries",
    blurb: "Crystal Cosmo · Stardust Revolution",
    speed: 210,
    arriveDistance: 8,
    attackRange: 100,
    attackCooldownMs: 300,
    attackDamage: 30,
    specialChargeMs: 10 * 1000,
    specialRange: 410,
    specialDamage: 999,
    specialName: "STARDUST REVOLUTION",
    specialStyle: "stardust",
    scale: 0.9,
    accent: 0xe8c8a0,
  },
  taurus: {
    id: "taurus",
    name: "Taurus",
    key: "taurus",
    blurb: "Titan strength · Great Horn",
    speed: 175,
    arriveDistance: 10,
    attackRange: 85,
    attackCooldownMs: 340,
    attackDamage: 42,
    specialChargeMs: 10 * 1000,
    specialRange: 380,
    specialDamage: 999,
    specialName: "GREAT HORN",
    specialStyle: "horn",
    scale: 0.95,
    accent: 0xd4a85a,
  },
  gemini: {
    id: "gemini",
    name: "Gemini",
    key: "gemini",
    blurb: "Twin Cosmo · Galaxian Explosion",
    speed: 220,
    arriveDistance: 8,
    attackRange: 90,
    attackCooldownMs: 280,
    attackDamage: 34,
    specialChargeMs: 10 * 1000,
    specialRange: 420,
    specialDamage: 999,
    specialName: "GALAXIAN EXPLOSION",
    specialStyle: "galaxian",
    scale: 0.9,
    accent: 0x6ec8e0,
  },
  cancer: {
    id: "cancer",
    name: "Cancer",
    key: "cancer",
    blurb: "Underworld gate · Sekishiki Meikai Ha",
    speed: 205,
    arriveDistance: 8,
    attackRange: 95,
    attackCooldownMs: 300,
    attackDamage: 32,
    specialChargeMs: 10 * 1000,
    specialRange: 400,
    specialDamage: 999,
    specialName: "SEKISHIKI MEIKAI HA",
    specialStyle: "underworld",
    scale: 0.9,
    accent: 0xc9a0e0,
  },
  leo: {
    id: "leo",
    name: "Leo",
    key: "leo",
    blurb: "Lightning fists · Lightning Plasma",
    speed: 250,
    arriveDistance: 8,
    attackRange: 95,
    attackCooldownMs: 240,
    attackDamage: 31,
    specialChargeMs: 10 * 1000,
    specialRange: 430,
    specialDamage: 999,
    specialName: "LIGHTNING PLASMA",
    specialStyle: "plasma",
    scale: 0.9,
    accent: 0xffc04a,
  },
  virgo: {
    id: "virgo",
    name: "Virgo",
    key: "virgo",
    blurb: "Buddha Cosmo · 108 prayer beads",
    speed: 200,
    arriveDistance: 8,
    attackRange: 110,
    attackCooldownMs: 320,
    attackDamage: 28,
    specialChargeMs: 10 * 1000,
    specialRange: 400,
    specialDamage: 999,
    specialName: "TENBU HORIN",
    specialStyle: "beads",
    scale: 0.9,
    accent: 0xe8d48a,
  },
  libra: {
    id: "libra",
    name: "Libra",
    key: "libra",
    blurb: "Balance arms · Libra Weapons",
    speed: 215,
    arriveDistance: 8,
    attackRange: 115,
    attackCooldownMs: 290,
    attackDamage: 33,
    specialChargeMs: 10 * 1000,
    specialRange: 440,
    specialDamage: 999,
    specialName: "LIBRA WEAPONS",
    specialStyle: "weapons",
    scale: 0.9,
    accent: 0xc8b070,
  },
  scorpio: {
    id: "scorpio",
    name: "Scorpio",
    key: "scorpio",
    blurb: "Scarlet sting · Scarlet Needle",
    speed: 235,
    arriveDistance: 8,
    attackRange: 120,
    attackCooldownMs: 260,
    attackDamage: 29,
    specialChargeMs: 10 * 1000,
    specialRange: 450,
    specialDamage: 999,
    specialName: "SCARLET NEEDLE",
    specialStyle: "needle",
    scale: 0.88,
    accent: 0xe05a6a,
  },
  sagittarius: {
    id: "sagittarius",
    name: "Sagittarius",
    key: "sagittarius",
    blurb: "Golden archer · Atomic Thunderbolt",
    speed: 245,
    arriveDistance: 8,
    attackRange: 130,
    attackCooldownMs: 260,
    attackDamage: 30,
    specialChargeMs: 10 * 1000,
    specialRange: 460,
    specialDamage: 999,
    specialName: "ATOMIC THUNDERBOLT",
    specialStyle: "thunderbolt",
    scale: 0.88,
    accent: 0xf0c45a,
  },
  capricorn: {
    id: "capricorn",
    name: "Capricorn",
    key: "capricorn",
    blurb: "Sacred blade · Excalibur",
    speed: 225,
    arriveDistance: 8,
    attackRange: 105,
    attackCooldownMs: 270,
    attackDamage: 36,
    specialChargeMs: 10 * 1000,
    specialRange: 420,
    specialDamage: 999,
    specialName: "EXCALIBUR",
    specialStyle: "excalibur",
    scale: 0.9,
    accent: 0xd8d0b0,
  },
  aquarius: {
    id: "aquarius",
    name: "Aquarius",
    key: "aquarius",
    blurb: "Absolute zero · Aurora Execution",
    speed: 210,
    arriveDistance: 8,
    attackRange: 110,
    attackCooldownMs: 300,
    attackDamage: 30,
    specialChargeMs: 10 * 1000,
    specialRange: 430,
    specialDamage: 999,
    specialName: "AURORA EXECUTION",
    specialStyle: "aurora",
    scale: 0.9,
    accent: 0x7ec8e8,
  },
  pisces: {
    id: "pisces",
    name: "Pisces",
    key: "pisces",
    blurb: "Demon roses · Bloody Rose",
    speed: 230,
    arriveDistance: 8,
    attackRange: 100,
    attackCooldownMs: 280,
    attackDamage: 31,
    specialChargeMs: 10 * 1000,
    specialRange: 410,
    specialDamage: 999,
    specialName: "BLOODY ROSE",
    specialStyle: "rose",
    scale: 0.88,
    accent: 0xe07098,
  },
};

export const GAME = {
  width: 960,
  height: 640,
  durationMs: 2 * 60 * 1000,
  patchMaxHp: 100,
  // Legacy aliases (Gemini defaults) used where hero isn't in scope yet
  geminiSpeed: 220,
  geminiArriveDistance: 8,
  geminiAttackRange: 90,
  geminiAttackCooldownMs: 280,
  geminiAttackDamage: 34,
  doubleClickMs: 280,
  specialChargeMs: 10 * 1000,
  specialAttackRange: 420,
  specialAttackDamage: 999,
  enemySpeed: 55,
  enemyHp: 30,
  enemyDamage: 5,
  enemyAttackCooldownMs: 900,
  spawnIntervalStartMs: 2800,
  spawnIntervalMinMs: 1600,
  // Broccoli pests — weights shift as the match progresses
  enemyTypes: {
    squirrel: {
      key: "enemy-squirrel",
      label: "Squirrel",
      hp: 30,
      speed: 55,
      damage: 5,
      attackCooldownMs: 900,
      scale: 0.85,
      shadowW: 34,
      shadowH: 12,
      body: { w: 40, h: 44, ox: 16, oy: 14 },
    },
    aphid: {
      key: "enemy-aphid",
      label: "Aphid",
      hp: 14,
      speed: 95,
      damage: 3,
      attackCooldownMs: 650,
      scale: 0.7,
      shadowW: 24,
      shadowH: 10,
      body: { w: 28, h: 30, ox: 18, oy: 18 },
      packChance: 0.55,
    },
    worm: {
      key: "enemy-worm",
      label: "Cabbage Worm",
      hp: 70,
      speed: 32,
      damage: 9,
      attackCooldownMs: 1100,
      scale: 0.95,
      shadowW: 46,
      shadowH: 14,
      body: { w: 48, h: 36, ox: 16, oy: 22 },
    },
  },
  athenaIntervalMs: 15 * 1000,
  athenaHealAmount: 35,
  // Pseudo-3D (WC3-style tilted view)
  pseudo3d: {
    farScale: 0.72,
    nearScale: 1.1,
    // Tiny at the rim, grow as they approach the broccoli
    enemyFarScale: 0.48,
    enemyNearScale: 1.18,
    heroFarScale: 0.58,
    heroNearScale: 1.14,
    spriteSquash: 0.9,
    shadowAlpha: 0.34,
  },
};

export const COLORS = {
  ground: 0x1a2a22,
  groundAccent: 0x24382d,
  gemini: 0xd4b45a,
  geminiAccent: 0x6ec8e0,
  broccoli: 0x3f8f4a,
  broccoliStem: 0x8fbf5a,
  enemy: 0xc45c48,
  enemyEye: 0xf2e6c8,
  hud: "#f3efe4",
  hudMuted: "#a8b5aa",
  danger: "#e07a5f",
  win: "#8fd19e",
};

/** Per-saint house backdrop (Sanctuary temples). Falls back to `default`. */
export const TEMPLES = {
  default: {
    id: "default",
    label: "Sacred Grove",
    skyTop: 0x1b3344,
    skyBottom: 0x0d1c22,
    hillFar: 0x152820,
    hillNear: 0x1a3428,
    ground: 0x1a2a22,
    groundAccent: 0x24382d,
    ringPrimary: 0x6ec8e0,
    ringSecondary: 0xd4b45a,
  },
  aries: {
    id: "aries",
    label: "Temple of the White Ram",
    // Painted backdrop: public/assets/aries-temple.png
    backdrop: "aries-temple",
    accent: 0xe8c890,
    ringPrimary: 0xd8d0b8,
    ringSecondary: 0xa8c0d8,
    // Floor medallion in the painted hall (lower than the doorway)
    patchX: 480,
    patchY: 500,
    // Golden Aries seal above the doorway
    iconX: 480,
    iconY: 132,
    heroSpawnOffsetY: 90,
  },
  taurus: {
    id: "taurus",
    label: "Temple of the Golden Bull",
    // Painted backdrop: public/assets/taurus-temple.png
    backdrop: "taurus-temple",
    accent: 0xd4a85a,
    ringPrimary: 0xe0c080,
    ringSecondary: 0xc07040,
    // Floor bull medallion in the painted hall
    patchX: 480,
    patchY: 500,
    // Golden Taurus seal above the doorway
    iconX: 480,
    iconY: 132,
    heroSpawnOffsetY: 95,
  },
  gemini: {
    id: "gemini",
    label: "Temple of the Twins",
    // Painted backdrop: public/assets/gemini-temple.png
    backdrop: "gemini-temple",
    accent: 0x6ec8e0,
    ringPrimary: 0xa8e0f0,
    ringSecondary: 0xd4b45a,
    // Floor twin medallion in the painted hall
    patchX: 480,
    patchY: 500,
    // Cyan-gold Gemini seal above the doorway
    iconX: 480,
    iconY: 132,
    heroSpawnOffsetY: 90,
  },
  cancer: {
    id: "cancer",
    label: "Temple of the Giant Crab",
    // Painted backdrop: public/assets/cancer-temple.png
    backdrop: "cancer-temple",
    accent: 0xc9a0e0,
    ringPrimary: 0xd8b8f0,
    ringSecondary: 0x6a40a0,
    // Floor crab medallion in the painted hall
    patchX: 480,
    patchY: 500,
    // Violet Cancer seal above the doorway
    iconX: 480,
    iconY: 132,
    heroSpawnOffsetY: 90,
  },
};
